const params=new URLSearchParams(location.search);const session=params.get('session')||params.get('room');const root=document.getElementById('app');let state={score:{votes:[]},likes:{},raconGifts:[],mekanGifts:[],wins:0,targetWins:20};
const esc=t=>String(t??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const initial=n=>esc(String(n||'K').slice(0,2).toUpperCase());
function avatar(n,u){return `<div class="avatar">${u?`<img src="${esc(u)}" referrerpolicy="no-referrer" onerror="this.style.display='none';this.parentElement.textContent='${initial(n)}'">`:initial(n)}</div>`}
function item(name,val,u=''){return `<div class="item"><div class="user">${avatar(name,u)}<span>${esc(name)}</span></div><div class="score">${esc(val)}</div></div>`}
function paint(){const p=location.pathname;let h='';if(p.includes('puanlama')){const v=state.score?.votes||[];const a=v.length?v.reduce((x,y)=>x+Number(y.value||0),0)/v.length:0;const left=state.score?.active&&state.score.endsAt?Math.max(0,Math.ceil((state.score.endsAt-Date.now())/1000))+' sn':'HAZIR';h=`<div class="stage"><div class="box"><div class="title">⭐ MS YAYIN · PUANLAMA</div><div class="sub">Canlı oylar</div><div class="big">${a.toFixed(1)}</div><div class="center"><span class="tag">${v.length} OY</span> <span class="tag">${left}</span></div><div class="list">${v.slice(0,16).map(x=>item(x.username,x.value+' PUAN',x.avatarUrl)).join('')||'<div class="empty">Henüz oy yok.</div>'}</div></div></div>`}
else if(p.includes('racon'))h=`<div class="stage"><div class="box"><div class="title">👑 RACON KRALLARI</div><div class="sub">Seçili hediye sahipleri</div><div class="list">${(state.raconGifts||[]).slice(0,16).map(x=>item(x.username,x.gift+(x.quantity>1?' ×'+x.quantity:''),x.avatarUrl)).join('')||'<div class="empty">Hediye bekleniyor.</div>'}</div></div></div>`;
else if(p.includes('mekan'))h=`<div class="stage"><div class="box"><div class="title">🏠 MEKAN SAHİBİ</div><div class="sub">Seçili hediye sahipleri</div><div class="list">${(state.mekanGifts||[]).slice(0,16).map(x=>item(x.username,x.gift+(x.quantity>1?' ×'+x.quantity:''),x.avatarUrl)).join('')||'<div class="empty">Hediye bekleniyor.</div>'}</div></div></div>`;
else if(p.includes('begeni')){const l=Object.entries(state.likes||{}).sort((a,b)=>(b[1]?.count||0)-(a[1]?.count||0));h=`<div class="stage"><div class="box"><div class="title">❤️ BEĞENİ SIRALAMASI</div><div class="grid">${l.slice(0,3).map((x,i)=>`<div class="rank"><b>#${i+1}</b>${avatar(x[0],x[1]?.avatarUrl)}<span>${esc(x[0])}</span><span>${(x[1]?.count||0).toLocaleString('tr-TR')} ❤️</span></div>`).join('')||'<div class="empty">Beğeni bekleniyor.</div>'}</div><div class="list">${l.slice(3,18).map(x=>item(x[0],(x[1]?.count||0)+' ❤️',x[1]?.avatarUrl)).join('')}</div></div></div>`}
else h=`<div class="stage"><div class="box"><div class="title">🏆 MS YAYIN · WIN</div><div class="win">${state.wins||0}</div><div class="slash">/ ${state.targetWins||20} WIN</div></div></div>`;root.innerHTML=h}
if(session){const s=io();s.on('connect',()=>s.emit('join',session));s.on('state:update',x=>{state=x;paint()})}paint();setInterval(paint,500);
