const http = require('http');
const { URL } = require('url');

const PORT = Number(process.env.PORT || 10000);
const server = http.createServer();
const state = {
  username: '', connected: false,
  scoring: false, scoreDuration: 15, scoreEndsAt: 0, votes: [],
  likes: {}, giftRules: { racon: '', mekan: '' },
  giftCatalog: ['Aslan','Galaksi','TikTok Universe','Gül','Finger Heart'],
  racon: {}, mekan: {}, lastRacon: null, lastMekan: null,
  wins: 0, maxWins: 20, penalty: 20
};
let scoreTimer = null;

function clean(v){ return String(v ?? '').replace(/^@+/, '').trim().slice(0,80); }
function gift(v){ return String(v ?? '').trim().slice(0,80); }
function norm(v){ return gift(v).toLocaleLowerCase('tr-TR'); }
function json(res, code, data){ const body=JSON.stringify(data); res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}); res.end(body); }
function html(res, body){ res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}); res.end(body); }
function sendError(res, code, message){ json(res, code, {ok:false,message}); }
function publicState(){
  const votes=state.votes.slice(-100).reverse();
  const users=new Set(state.votes.map(v=>v.username));
  const avg=state.votes.length ? Number((state.votes.reduce((a,v)=>a+v.score,0)/state.votes.length).toFixed(2)) : 0;
  return {username:state.username,connected:state.connected,scoring:state.scoring,scoreDuration:state.scoreDuration,scoreEndsAt:state.scoreEndsAt,average:avg,participants:users.size,votes,likes:Object.entries(state.likes).map(([username,x])=>({username,likeCount:x.count})).sort((a,b)=>b.likeCount-a.likeCount),giftRules:{...state.giftRules},giftCatalog:[...state.giftCatalog],racon:Object.values(state.racon).sort((a,b)=>b.count-a.count),mekan:Object.values(state.mekan).sort((a,b)=>b.count-a.count),lastRacon:state.lastRacon,lastMekan:state.lastMekan,wins:state.wins,maxWins:state.maxWins,penalty:state.penalty};
}
function addVote(u,score){ if(!state.scoring) return; const n=Number(score); if(!Number.isInteger(n)||n<1||n>10)return; state.votes.push({username:clean(u)||'bilinmeyen',score:n,at:Date.now()}); state.votes=state.votes.slice(-300); }
function addLike(u,count){ const user=clean(u)||'bilinmeyen'; const n=Math.max(1,Number(count)||1); state.likes[user]={count:(state.likes[user]?.count||0)+n}; }
function addGift(u,g){ const user=clean(u)||'bilinmeyen'; const gg=gift(g)||'Hediye'; const key=norm(gg); if(!state.giftCatalog.some(x=>norm(x)===key))state.giftCatalog.push(gg); if(state.giftRules.racon&&norm(state.giftRules.racon)===key){state.racon[user]={username:user,count:(state.racon[user]?.count||0)+1,gift:gg};state.lastRacon={username:user,gift:gg,at:Date.now()};} if(state.giftRules.mekan&&norm(state.giftRules.mekan)===key){state.mekan[user]={username:user,count:(state.mekan[user]?.count||0)+1,gift:gg};state.lastMekan={username:user,gift:gg,at:Date.now()};}}
function startScore(){ if(scoreTimer)clearTimeout(scoreTimer); state.votes=[]; state.scoring=true; state.scoreEndsAt=Date.now()+state.scoreDuration*1000; scoreTimer=setTimeout(()=>{state.scoring=false;state.scoreEndsAt=0;},state.scoreDuration*1000); }
function stopScore(){ if(scoreTimer)clearTimeout(scoreTimer); scoreTimer=null; state.scoring=false;state.scoreEndsAt=0; }
function pageTitle(path){ return ({'/':'Yayın Bağlantısı','/puanlama':'Puanlama','/racon':'Racon Kralları','/mekan':'Mekan Sahibi','/begeni':'Beğeni Sıralaması','/win':'WIN Sayacı','/test':'Test Merkezi','/rehber':'Kullanım Rehberi'})[path] || 'Yayın Bağlantısı'; }
function panelPage(path){
  const content = {
    '/': `\n<div class="card hero"><h2>🔴 TikTok Yayın Bağlantısı</h2><p>Sadece kullanıcı adını yazıp bağlan. <b>Room yok.</b></p><div class="row"><input id="tt" placeholder="@kullaniciadi" value="${esc(state.username)}"><button onclick="connectTikTok()">BAĞLAN</button><button class="secondary" onclick="disconnectTikTok()">BAĞLANTIYI KES</button></div><div id="connMsg" class="muted" style="margin-top:12px">Durum: ${state.connected?'🟢 Bağlı':'🔴 Bağlı değil'}</div></div>`,
    '/puanlama': scoreContent(),
    '/racon': categoryContent('racon','👑 Racon Kralları','racon'),
    '/mekan': categoryContent('mekan','🏠 Mekan Sahibi','mekan'),
    '/begeni': likesContent(),
    '/win': winContent(),
    '/test': testContent(),
    '/rehber': guideContent()
  }[path] || '<div class="card"><h2>Sayfa bulunamadı</h2><a href="/">Ana sayfaya dön</a></div>';
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MS YAYIN - ${pageTitle(path)}</title><style>${CSS}</style></head><body><div class="layout"><aside class="side"><div class="brand">🔥 MS <b>YAYIN</b></div><nav>${navLink('/', '🔴 Yayın Bağlantısı', path)}${navLink('/puanlama','⭐ Puanlama',path)}${navLink('/racon','👑 Racon Kralları',path)}${navLink('/mekan','🏠 Mekan Sahibi',path)}${navLink('/begeni','❤️ Beğeni Sıralaması',path)}${navLink('/win','🏆 WIN Sayacı',path)}${navLink('/test','🧪 Test Merkezi',path)}${navLink('/rehber','📖 Kullanım Rehberi',path)}</nav></aside><main class="main"><div class="top"><div><h1>${pageTitle(path)}</h1><div class="muted">Tek kullanıcı adı • Room yok • doğrudan sayfalar</div></div><div class="notice">${state.connected?'🟢':'🔴'} ${esc(state.username||'Bağlı değil')}</div></div>${content}</main></div><script>${JS}</script></body></html>`;
}
function navLink(h,t,p){return `<a href="${h}" class="${h===p?'active':''}">${t}</a>`}
function scoreContent(){const left=state.scoring?Math.max(0,Math.ceil((state.scoreEndsAt-Date.now())/1000)):0;const rows=state.votes.slice(-100).reverse().map(v=>`<tr><td>@${esc(v.username)}</td><td>${v.score}</td></tr>`).join('');return `<div class="card"><div class="row"><label>Süre <input id="dur" type="number" min="1" max="3600" value="${state.scoreDuration}"> sn</label><button class="secondary" onclick="saveDuration()">SÜREYİ KAYDET</button><button class="green" onclick="startScore()">BAŞLAT</button><button class="danger" onclick="stopScore()">BİTİR</button></div></div><div class="grid"><div class="card"><div class="muted">Ortalama</div><div class="stat">${state.votes.length?(state.votes.reduce((a,v)=>a+v.score,0)/state.votes.length).toFixed(2):'0'}</div></div><div class="card"><div class="muted">Katılımcı</div><div class="stat">${new Set(state.votes.map(v=>v.username)).size}</div></div><div class="card"><div class="muted">Kalan</div><div class="stat">${state.scoring?left+' sn':'—'}</div></div><div class="card"><div class="muted">Durum</div><div class="stat">${state.scoring?'🟢 AKTİF':'⚪ BEKLEMEDE'}</div></div></div><div class="card"><h3>Oy verenler</h3><table><tr><th>Kullanıcı</th><th>Puan</th></tr>${rows||'<tr><td colspan="2" class="empty">Henüz oy yok.</td></tr>'}</table></div><div class="card"><h3>Overlay</h3><div class="link">${origin()}/overlay/puanlama</div></div>`}
function giftOptions(selected){return state.giftCatalog.map(g=>`<option value="${esc(g)}" ${g===selected?'selected':''}>${esc(g)}</option>`).join('')}
function categoryContent(type,title){const arr=type==='racon'?Object.values(state.racon):Object.values(state.mekan);const rows=arr.sort((a,b)=>b.count-a.count).map((x,i)=>`<tr><td>${i<3?['🥇','🥈','🥉'][i]:i+1+'.'} @${esc(x.username)}</td><td>${x.count}x</td><td>${esc(x.gift)}</td></tr>`).join('');return `<div class="card"><h2>${title}</h2><p class="muted">Hediyeyi listeden seç. O hediye geldiğinde gönderen otomatik eklenir.</p><div class="row"><select id="gift">${giftOptions(state.giftRules[type])}</select><button class="green" onclick="saveGiftRule('${type}')">AKTİF ET</button><button class="secondary" onclick="clearGiftRule('${type}')">KALDIR</button></div><p>Aktif hediye: <b>${esc(state.giftRules[type]||'Yok')}</b></p></div><div class="card"><h3>Liste</h3><table><tr><th>Kullanıcı</th><th>Adet</th><th>Hediye</th></tr>${rows||'<tr><td colspan="3" class="empty">Henüz kayıt yok.</td></tr>'}</table></div><div class="card"><h3>Overlay</h3><div class="link">${origin()}/overlay/${type}</div></div>`}
function likesContent(){const rows=Object.entries(state.likes).map(([username,x])=>({username,likeCount:x.count})).sort((a,b)=>b.likeCount-a.likeCount).map((x,i)=>`<tr><td>${i<3?['🥇','🥈','🥉'][i]:i+1+'.'} @${esc(x.username)}</td><td>${x.likeCount.toLocaleString('tr-TR')} ❤️</td></tr>`).join('');return `<div class="card"><div class="row between"><h2>❤️ Beğeni Sıralaması</h2><button class="danger" onclick="resetLikes()">SIFIRLA</button></div><table><tr><th>Kullanıcı</th><th>Beğeni</th></tr>${rows||'<tr><td colspan="2" class="empty">Henüz beğeni yok.</td></tr>'}</table></div><div class="card"><h3>Overlay</h3><div class="link">${origin()}/overlay/begeni</div></div>`}
function winContent(){return `<div class="card"><h2>🏆 WIN Sayacı</h2><div class="bigWin">${String(state.wins).padStart(2,'0')} / ${state.maxWins}</div><p class="muted">-${state.penalty} CEZA</p><div class="row"><button onclick="win(1)">+ WIN</button><button class="danger" onclick="win(-1)">- WIN</button><button class="gold" onclick="win(0)">SIFIRLA</button></div></div><div class="card"><h3>Overlay</h3><div class="link">${origin()}/overlay/win</div></div>`}
function testContent(){return `<div class="card"><h2>🧪 Test Merkezi</h2><p class="muted">Gerçek yayın olayı gelmiş gibi sistemi test et.</p><div class="row"><input id="tu" value="test_kullanici" placeholder="Kullanıcı"><input id="ts" type="number" min="1" max="10" value="10"><button onclick="testVote()">TEST PUANI</button></div><br><div class="row"><input id="tg" value="Aslan" placeholder="Hediye"><button onclick="testGift()">TEST HEDİYE</button></div><br><div class="row"><input id="tl" type="number" value="100"><button onclick="testLike()">TEST BEĞENİ</button></div></div>`}
function guideContent(){return `<div class="card"><h2>📖 Kullanım Rehberi</h2><ol><li>Yayın Bağlantısı'nda TikTok kullanıcı adını yaz.</li><li>Puanlama süresini ayarla ve başlat.</li><li>Racon/Mekan'da hediyeyi dropdown'dan seç.</li><li>Test Merkezi ile sistemi dene.</li><li>Overlay linkini OBS/TikTok Live Studio Browser Source olarak ekle.</li></ol><p class="muted">Bu sürüm Room kullanmaz ve tüm menüler gerçek URL'lere gider.</p></div>`}
function origin(){return ""}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function readBody(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>100000)req.destroy()});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}});req.on('error',reject)})}

async function api(req,res,path){
  let body={}; if(req.method==='POST'){try{body=await readBody(req)}catch(e){return sendError(res,400,'Geçersiz veri.')}}
  if(req.method==='GET'&&path==='/state') return json(res,200,publicState());
  if(req.method!=='POST') return sendError(res,405,'Method not allowed');
  if(path==='/connect'){const u=clean(body.username);if(!u)return sendError(res,400,'TikTok kullanıcı adı gerekli.');state.username=u;state.connected=false;return json(res,200,{ok:true,message:'Kullanıcı adı kaydedildi. Gerçek TikTok bağlantısı sonraki adımda etkinleştirilecek.',state:publicState()});}
  if(path==='/disconnect'){state.username='';state.connected=false;return json(res,200,publicState());}
  if(path==='/score/settings'){const d=Number(body.duration);if(!Number.isFinite(d)||d<1||d>3600)return sendError(res,400,'Süre 1-3600 saniye arası olmalı.');state.scoreDuration=Math.floor(d);return json(res,200,publicState());}
  if(path==='/score/start'){startScore();return json(res,200,publicState());}
  if(path==='/score/stop'){stopScore();return json(res,200,publicState());}
  if(path==='/gift-rule'){const type=body.type,g=gift(body.gift);if(!['racon','mekan'].includes(type)||!g)return sendError(res,400,'Sistem ve hediye seçilmelidir.');state.giftRules[type]=g;if(!state.giftCatalog.some(x=>norm(x)===norm(g)))state.giftCatalog.push(g);return json(res,200,publicState());}
  if(path==='/gift-rule/clear'){const type=body.type;if(!['racon','mekan'].includes(type))return sendError(res,400,'Geçersiz sistem.');state.giftRules[type]='';return json(res,200,publicState());}
  if(path==='/likes/reset'){state.likes={};return json(res,200,publicState());}
  if(path==='/win'){const c=Number(body.change);if(c===0)state.wins=0;else if(c===1)state.wins=Math.min(state.maxWins,state.wins+1);else if(c===-1)state.wins=Math.max(0,state.wins-1);else return sendError(res,400,'Geçersiz WIN işlemi.');return json(res,200,publicState());}
  if(path==='/test/vote'){if(!state.scoring)startScore();addVote(body.username||'test_kullanici',body.score||10);return json(res,200,publicState());}
  if(path==='/test/gift'){addGift(body.username||'test_kullanici',body.gift||'Aslan');return json(res,200,publicState());}
  if(path==='/test/like'){addLike(body.username||'test_kullanici',body.count||100);return json(res,200,publicState());}
  return sendError(res,404,'API yolu bulunamadı.');
}

const CSS=`*{box-sizing:border-box}body{margin:0;background:#08090d;color:#f5f5f5;font-family:Segoe UI,Arial,sans-serif}.layout{display:flex;min-height:100vh}.side{position:fixed;left:0;top:0;bottom:0;width:250px;background:#10131a;border-right:1px solid #252a35;padding:22px}.brand{font-weight:900;font-size:23px;margin-bottom:22px}.brand b{color:#e53935}.nav a{display:block;text-decoration:none;color:#d5d8e0;padding:12px 11px;border-radius:10px;margin:4px 0;font-weight:750}.nav a:hover,.nav a.active{background:#1c212d;color:#fff}.main{margin-left:250px;padding:30px;max-width:1500px;width:calc(100% - 250px)}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:20px}.top h1{margin:0 0 5px}.muted{color:#9098aa}.card{background:#131721;border:1px solid #282e3a;border-radius:16px;padding:20px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.stat{font-size:32px;font-weight:900;margin-top:6px}.bigWin{font-size:64px;font-weight:950}.row{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.between{justify-content:space-between}input,select{background:#0e1117;color:#fff;border:1px solid #303747;border-radius:10px;padding:11px;min-width:170px}button{border:0;border-radius:10px;padding:11px 15px;color:#fff;background:#e53935;font-weight:800;cursor:pointer}button.secondary{background:#242a36}button.green{background:#1c9a5b}button.gold{background:#9a741e}button.danger{background:#a9212d}.table,table{width:100%;border-collapse:collapse}.table th,.table td,th,td{padding:11px 8px;border-bottom:1px solid #272d39;text-align:left}.empty{text-align:center;color:#8e95a5;padding:22px}.link{padding:10px;background:#0d1016;border:1px solid #252b36;border-radius:9px;word-break:break-all;font-size:13px}.notice{padding:12px 14px;border-radius:10px;background:#171c25;border:1px solid #2b313e}.hero{padding:28px}@media(max-width:900px){.side{width:210px}.main{margin-left:210px;width:calc(100% - 210px)}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.layout{display:block}.side{position:static;width:100%}.main{margin:0;width:100%}.grid{grid-template-columns:1fr}}`;
const JS=`async function post(u,b){const r=await fetch('/api'+u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b||{})});const x=await r.json();if(!r.ok)throw Error(x.message||'İşlem başarısız');return x}async function refresh(){try{location.reload()}catch(_){}}async function connectTikTok(){try{const x=await post('/connect',{username:document.getElementById('tt').value});document.getElementById('connMsg').textContent=x.message}catch(e){alert(e.message)}}async function disconnectTikTok(){await post('/disconnect');location.reload()}async function saveDuration(){await post('/score/settings',{duration:document.getElementById('dur').value});location.reload()}async function startScore(){await post('/score/start');location.reload()}async function stopScore(){await post('/score/stop');location.reload()}async function saveGiftRule(type){const g=document.getElementById('gift').value;try{await post('/gift-rule',{type,gift:g});location.reload()}catch(e){alert(e.message)}}async function clearGiftRule(type){await post('/gift-rule/clear',{type});location.reload()}async function resetLikes(){await post('/likes/reset');location.reload()}async function win(c){await post('/win',{change:c});location.reload()}async function testVote(){await post('/test/vote',{username:document.getElementById('tu').value,score:document.getElementById('ts').value});location.reload()}async function testGift(){await post('/test/gift',{username:document.getElementById('tu').value,gift:document.getElementById('tg').value});location.reload()}async function testLike(){await post('/test/like',{username:document.getElementById('tu').value,count:document.getElementById('tl').value});location.reload()}`;

function overlay(type){ return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MS YAYIN OVERLAY</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;color:#fff;font-family:Arial,sans-serif}.wrap{width:100%;height:100%;display:grid;place-items:center}.box{min-width:380px;max-width:88%;background:rgba(7,8,12,.9);border:1px solid rgba(255,255,255,.14);border-radius:18px;padding:24px 28px;text-align:center}.title{font-size:26px;font-weight:900;margin-bottom:10px}.big{font-size:58px;font-weight:950}.row{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid rgba(255,255,255,.12)}</style></head><body><div class="wrap"><div id="box" class="box">Bekleniyor...</div></div><script>const type=${JSON.stringify(type)};const box=document.getElementById('box');const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));function draw(s){let h='';if(type==='puanlama')h=s.scoring?'<div class="title">⭐ PUANLAMA</div><div class="big">'+s.average+'</div><div>'+s.participants+' katılımcı · '+Math.max(0,Math.ceil((s.scoreEndsAt-Date.now())/1000))+' sn</div>':'<div class="title">⭐ PUANLAMA</div><div>Bekleniyor</div>';else if(type==='racon')h='<div class="title">👑 RACON KRALI</div><div class="big">'+(s.lastRacon?'@'+esc(s.lastRacon.username):'')+'</div><div>'+(s.lastRacon?esc(s.lastRacon.gift):'Hediye bekleniyor')+'</div>';else if(type==='mekan')h='<div class="title">🏠 MEKAN SAHİBİ</div><div class="big">'+(s.lastMekan?'@'+esc(s.lastMekan.username):'')+'</div><div>'+(s.lastMekan?esc(s.lastMekan.gift):'Hediye bekleniyor')+'</div>';else if(type==='begeni')h='<div class="title">❤️ BEĞENİ SIRALAMASI</div>'+s.likes.slice(0,10).map((x,i)=>'<div class="row"><span>'+((i<3)?['🥇','🥈','🥉'][i]:(i+1)+'.')+' @'+esc(x.username)+'</span><b>'+Number(x.likeCount).toLocaleString('tr-TR')+'</b></div>').join('');else if(type==='win')h='<div class="title">🏆 WIN</div><div class="big">'+String(s.wins).padStart(2,'0')+'/'+s.maxWins+'</div><div>-'+s.penalty+' CEZA</div>';else h='<div class="title">🔥 MS YAYIN</div><div class="big">⭐ '+s.average+'</div><div>🏆 '+String(s.wins).padStart(2,'0')+'/'+s.maxWins+'</div>';box.innerHTML=h}async function poll(){try{const s=await fetch('/api/state').then(r=>r.json());draw(s)}catch(_){} }poll();setInterval(poll,500)</script></body></html>` }

server.on('request',async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return await api(req,res,u.pathname.slice(4));if(u.pathname.startsWith('/overlay/'))return html(res,overlay(['puanlama','racon','mekan','begeni','win','all'].includes(u.pathname.slice(9))?u.pathname.slice(9):'all'));if(['/','/puanlama','/racon','/mekan','/begeni','/win','/test','/rehber'].includes(u.pathname))return html(res,panelPage(u.pathname));return html(res,'<!doctype html><meta charset="utf-8"><h1>Sayfa bulunamadı</h1><a href="/">Ana sayfa</a>')}catch(e){sendError(res,500,e.message)}});
server.listen(PORT,'0.0.0.0',()=>console.log('MS YAYIN running on '+PORT));
